### PR TITLE
FIX write_proc for kernels >3.10

### PR DESCRIPTION
**Pull request by iamslan**
Resolving #1

### CODE REVIEW

**Comment by williamklein** [comment]
Resolving #1

**Comment by derpston** [comment]
Good, thank you! What kernel version have you tested this with?

**Comment by iamslan** [comment]
Linux raspberrypi 3.18.11+ #781 PREEMPT Tue Apr 21 18:02:18 BST 2015 armv6l GNU/Linux

**Comment by derpston** [comment]
I see the latest version of Raspbian ships 3.18, so I'm happy to just merge this and discard backward compatibility for old Raspbian versions with kernel versions < 3.10. That means I should update my own running copy of this. :)

Thanks for the contribution.

**Pull request merged**
